#ifndef _UNABTO_CONFIG_H
#define _UNABTO_CONFIG_H

#define NABTO_LOG_SEVERITY_FILTER   NABTO_LOG_SEVERITY_LEVEL_TRACE
#define NABTO_ENABLE_UCRYPTO        1
#define NABTO_ENABLE_TCP_FALLBACK   1

#endif
